### ISSUE TITLE
article UUID empty FFFAFFDCFFB2FF8FFF87FFC1FFD59B42

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#1]
This http://tb.plazi.org/GgServer/summary/FFFAFFDCFFB2FF8FFF87FFC1FFD59B42 has no content

![image](https://user-images.githubusercontent.com/4609956/82200626-885b7900-98ff-11ea-8eab-7e5dce6917f2.png)

**Comment by gsautter** [comment]
And this shows you why: https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+cont.pageCount+cont.treatCount+cont.bibRefCount&groupingFields=doc.articleUuid+cont.pageCount+cont.treatCount+cont.bibRefCount&FP-doc.articleUuid=FFFAFFDCFFB2FF8FFF87FFC1FFD59B42&format=HTML

There just don't seem to be any treatments marked in this one ... if you manually marked any, there might be a typo.

**Comment by myrmoteras** [comment]
I see. May be we should add a line that says that "This article includes no treatment(s))?

**Comment by flsimoes** [comment]
Guido already included it a couple of months ago.

![image](https://user-images.githubusercontent.com/3343086/82208940-d1e99b00-98e2-11ea-8070-3eb78a24eec8.png)
