### ISSUE TITLE
SRS stats: add Article ChecklistBank DatasetID and Article GBIF DatasetID from pensoft uploads to SRS

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#108]
can we add Article ChecklistBank DatasetID and Article GBIF DatasetID from pensoft uploads to SRS stats? They are missing.

![image](https://github.com/plazi/treatmentBank/assets/4609956/fca748db-e270-4a02-a444-618bccb06ca1)
https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+doc.uploadUser+bib.year+bib.source+pubLnk.articleDoi+pubLnk.articleGbifId+pubLnk.articleClbId+pubLnk.articleZenodoDepId+tax.orderEpithet&groupingFields=doc.articleUuid+doc.uploadUser+bib.year+bib.source+pubLnk.articleDoi+pubLnk.articleGbifId+pubLnk.articleClbId+pubLnk.articleZenodoDepId+tax.orderEpithet&orderingFields=bib.year&FP-doc.uploadUser=%25ensoft&FP-tax.orderEpithet=Chiroptera&format=HTML

**Comment by gsautter** [comment]
For BDJ we are not exporting to DwCA, as Pensoft do that themselves ... hard to get those IDs if they don't come with the original TaxPub that we import.

Added the ChecklistBank IDs for all other articles.
