### ISSUE TITLE
Add a comment/error button to TB pages

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#117]
@gsautter @flsimoes @jugiora 

Suggestion: can we add a button “report and error” or similar on the TB side , eg  
![image](https://github.com/plazi/treatmentBank/assets/4609956/c3dd62fa-f1cc-4e18-9cc4-bcb85171c494)

or somewhere else, which creates an issue in https://github.com/plazi/community/issues  similar to what GBIF does 
 
![image](https://github.com/plazi/treatmentBank/assets/4609956/492ee10b-17cb-4dbf-8707-cc9ca0c27f40)

https://github.com/plazi/community/issues/new?body=Please%20leave%20your%20comment%20here...%0A%0A**Context**%0A%5BGBIF%20occurrence%5D(https%3A%2F%2Fwww.gbif.org%2Foccurrence%2F2628872471)%0A%5BPlazi%20reference%5D(https://treatment.plazi.org/id/F442953B2E6DEF72FF1BFBA5FE6C7AE0#CC832E702E6DEF72FB86FB66FE6C7AE0)

https://github.com/plazi/community/issues/new?

https://treatment.plazi.org/id/F442953B2E6DEF72FF1BFBA5FE6C7AE0#CC832E702E6DEF72FB86FB66FE6C7AE0)  

https://www.gbif.org/occurrence/2628872471

ideally it includes the link to the source treatment

**Comment by jugiora** [comment]
I totally agree with that. I think this way we could increase user involvement and make the search more interesting too. Our community channel on Github has received few comments.

**Comment by gsautter** [comment]
Added a little something ... top right of the treatment pages, in the menu bar next to the "Search" button ... does the same thing as the corresponding button in GBIF.

**Comment by gsautter** [comment]
Example: look at https://tb.plazi.org/GgServer/html/C615EC3AB7795E4D8ED5FC47F4AC8103 (the one I just sent a test ticket from)
