### ISSUE TITLE
wrong combination of authorities

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#120]
This is is a wrong combination of authorities  in this `comb. nov.`

![image](https://github.com/user-attachments/assets/d232c507-a94c-4ab8-bff4-063f55017173)

https://tb.plazi.org/GgServer/html/EE3587F5CB4FFFCEFF5BFCC96CF8F622

**Comment by valdenar** [comment]
I corrected the authorities and it has already been updated on TB.
