### ISSUE TITLE
possible corruption in zip archives

### ISSUE THREAD

**Issue by punkish** [plazi/treatmentBank#124]
my (various) unzip programs are encountering error when trying to unzip the [Dec 2024 monthly archive](https://tb.plazi.org/GgServer/dumps/plazi.zenodeo.monthly.zip). Has anything changed in the way the archives are created, or is there possibly some other issue which is causing an error when trying to unzip them?

**update:** fwiw, I tested the weekly and the daily zip files, and they are both ok, but the monthly one fails. Could you please check?

Many thanks for looking into this.

Puneet

cc @myrmoteras @gsautter

**Comment by gsautter** [comment]
The monthly dump is just the same as the weekly and daily (and the annual full dump, for that matter) ... only thing is that it's fairly large this month, as the mass update in late November changed lots of treatments ...

Considering the fact that most, if not all, zip utilities cache the decompressed data in some temporary folder, could it be you're just low on disk space? at least on whichever drive your temporary folder is located on?

**Comment by punkish** [comment]
on my laptop with almost 400GB of space free

```
zips git:(master) ✗ unzip -t plazi.zenodeo.daily.zip
Archive:  plazi.zenodeo.daily.zip
    testing: 039887E7FF29FF99FD52FCDF8524FB44.xml   OK
    testing: 039887E7FF11FFA1FD98F97784BAF880.xml   OK
    …
    testing: FCDE0DE6BCD353D4A285C4E7776D3297.xml   OK
    testing: index.xml                OK
No errors detected in compressed data of plazi.zenodeo.daily.zip.

zips git:(master) ✗ unzip -t plazi.zenodeo.weekly.zip
Archive:  plazi.zenodeo.weekly.zip
    testing: 039B3D1FFFFAFFA7FF40FA4DFD5879E2.xml   OK
    testing: 1CBF7D027626586CA585C0699EF45551.xml   OK
    …
    testing: FCDE0DE6BCD353D4A285C4E7776D3297.xml   OK
    testing: index.xml                OK
No errors detected in compressed data of plazi.zenodeo.weekly.zip

zips git:(master) ✗ unzip -t plazi.zenodeo.monthly.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

Exactly the same results on the Ubuntu VPS where the apps are hosted.

Also, the same results with other unzip/unarchive programs. As far as I can tell, there is something wrong with just the plazi.zenodeo.monthly.zip. It is 1,082,471,563 bytes (~1.08 GB) on my disk.

**Comment by gsautter** [comment]
> Also, the same results with other unzip/unarchive programs. As far as I can tell, there is something wrong with just the plazi.zenodeo.monthly.zip. It is 1,082,471,563 bytes (~1.08 GB) on my disk.

I guess you found the culprit there ... the `plazi.zenodeo.monthly.zip` file on the server is 2,922,351,258 bytes, so this might well be down to an incomplete download.

**Comment by punkish** [comment]
yes, seems like I have an incomplete download. But, for whatever reason, I am unable to download anything different. I've tried a direct download via curl on both my laptop and the VPS server, and also by clicking on the link in the browser on my laptop… so, two different computers, three different methods, and each time I get the 1.08 GB file. I don't know the reason behind this anomaly and I don't know how to solve it.

See the console output below

```
➜  zips git:(master) $ curl -O https://tb.plazi.org/GgServer/dumps/plazi.zenodeo.monthly.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1032M    0 1032M    0     0  9009k      0 --:--:--  0:01:57 --:--:-- 9263k
➜  zips git:(master) $ ll
-rw-r--r--  1 punkish  staff   1.0G Dec 22 20:10 plazi.zenodeo.monthly.zip
zips git:(master) $ du -h p*
1.0G	plazi.zenodeo.monthly.zip
```

**Comment by gsautter** [comment]
Will check soon as I get on a cable connection ... downloading multiple 3 GB via my DSL  might be a bit slow.

**Comment by myrmoteras** [comment]
Just remember, it's Christmas and thus a zip can wait until after the holidays, a family time, is over.

Also it's time for Guido to run updates etc.

Merry Christmas and happy new year

Donat



New species of the day<https://tb.plazi.org/GgServer/static/newToday.html>
Plazi<https://plazi.org/>
Bouchout+10 symposium<https://bouchoutdeclaration2024.org/>, August 21-23, 2024
________________________________

**Comment by gsautter** [comment]
@punkish try downloading from `http://tb.plazi.org/dumps/plazi.zenodeo.monthly.zip` instead of `http://tb.plazi.org/GgServer/dumps/plazi.zenodeo.monthly.zip` ... the former link bypasses Tomcat via a direct link from our nginx proxy ... Tomcat seems to be producing garbage headers if download file sizes exceed 31 bits ...

**Comment by punkish** [comment]
Thank you, this works. Just tested it on my laptop, and now redoing it on the server. Many thanks for investigating and resolving this. I am closing this issue now.
