### ISSUE TITLE
changing of treatment structure leads to deprecated Zenodo records

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#25]
https://publication.plazi.org/GgServer/summary/E568116C2276FF85FF9D404A6854FFFB

I fixed this new genus and species that have been one treatment https://publication.plazi.org/GgServer/html/195169142273FF80FF1344FC69E6FB12 into a treatment for the new genus https://publication.plazi.org/GgServer/html/195169142273FF80FF1344FC69E6FB12 and another for a new species https://publication.plazi.org/GgServer/html/195169142273FF88FF1344BB6D3CFB30.

Now both the Zenodo DOI at the taxon level result in deprecated 
![image](https://user-images.githubusercontent.com/4609956/150770749-dd92f446-320f-48aa-8269-cd0d50be0f03.png)

**Comment by gsautter** [comment]
First thing that jumps my eye here is that all three treatments you linked above have the same deposition ID in Zenodo ... that should not be the case.
Further, Zenodo depositions don't get deprecated unless you explicitly set the `ID-Zenodo-Dep` to `-2`, in which case you also need to remove the `ID-DOI` attribute (and for figures the `httpUri` attribute on top of the former two).

Can you run me through the exact order of operations that lead up to this situation?

**Comment by myrmoteras** [comment]
not sure, whether I can recapitulate:
1. I split the original gen and sp nov treatment
2. I split the subSubSections and renamed them
3. I marked in the genus treatment https://publication.plazi.org/GgServer/html/195169142273FF80FF1344FC69E6FB12 "type species" as taxonomic name and added the attributes from the type species https://publication.plazi.org/GgServer/html/195169142273FF88FF1344BB6D3CFB30

**Comment by gsautter** [comment]
If you split the original treatment, that sure changes the UUIDs (as it should), the changes to the `subSubSection`s doesn't do anything in this regard.
On splitting the treatment (or any other annotation), all the attributes except for the UUID are copied. If the treatment you split is already on Zenodo (as indicated by the presence of the `ID-Zenodo-Dep` attribute), you need to set it to `-2` to have the original deposition replaced/deprecated. The two new treatments then automatically go out to Zenodo (provided the QC doesn't have any objections).

How two mingled treatments were able to even get exported to Zenodo together is a different question ... the QC _should_ catch cases like this ...

**Comment by gsautter** [comment]
Did the -2 thing now ... the two new treatments should show up with sensible deposition numbers in a little while.

Looking the the article, this treatment boundary is pretty much impossible to spot, especially since the species isn't even in a heading ... might need to give a thought to combined genus/species treatments for such cases, most likely using the type species as the nomenclature section.
Left to hope that not too many journals have such convoluted treatments ...

**Comment by myrmoteras** [comment]
TX 
do not think more about this. This is rare, not worth developing code.

I parked the hint here https://github.com/plazi/treatmentBank/blob/master/Editing_annotations.md, and will continue with the intention to revise our manual for the teaching via POA
