### ISSUE TITLE
figures not linked since Feb 1.

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#34]
@gsautter is there a reason that the figures in the recently batch processed articles (since Feb 1) are not linked to the images?

Could be that there is a Zenodo issue? https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.gbifId+doc.zenodoDepId&groupingFields=doc.articleUuid+doc.gbifId+doc.zenodoDepId&FP-doc.articleUuid=FFC07C53B27DBE37FFD19038FFEAFFE2&format=HTML

e.g. https://tb.plazi.org/GgServer/summary/FFC07C53B27DBE37FFD19038FFEAFFE2 
![image](https://user-images.githubusercontent.com/4609956/152311825-223ebd7b-56ec-40cf-9f0b-bb34e301f977.png)

https://tb.plazi.org/GgServer/summary/FFFF7518FFBD1432FF8A2D7CA4693666a
![image](https://user-images.githubusercontent.com/4609956/152311948-42a30f3c-7989-4c0d-8f6b-d57ce7b95ae7.png)

https://tb.plazi.org/GgServer/summary/FF9F895C2F5BFFD79154FFEFFFFEFFC4
![image](https://user-images.githubusercontent.com/4609956/152312162-16543ac4-25cb-4d86-9bf0-24ce46df121b.png)

**Comment by gsautter** [comment]
Sorry about that ... the figures will be linked as used to, just taking a bit longer right now, as the Zenodo uplink is backlogged a bit right now ... a result of the all-out GBIF record key back-import (which we need for BiCiCL anyway) that caused a flurry of updates.

On the plus side, this finally also revisits all the IMFs processed before we introduced the gatekeeper in mid 2020, and runs QC on those as well.
