### ISSUE TITLE
taxonomic names in latest treatments

### ISSUE THREAD

**Issue by millerjeremya** [plazi/treatmentBank#39]
I was showing off the latest treatments on Plazi today (2022-03-08 (679)) to some colleagues. 
https://tb.plazi.org/GgServer/static/newToday.html
I noticed that several species are missing their epithets
![image](https://user-images.githubusercontent.com/4322250/157230554-52c16409-25cc-43ba-8f5f-5e2a2bf2513c.png)
A couple lacked higher taxon information
![image](https://user-images.githubusercontent.com/4322250/157230636-a1eb8b17-8bfc-4e66-9671-4f6facd79e62.png)
Several Drosophila were misclassified as fungi, and there were problems with species epithets missing their genera. 
![image](https://user-images.githubusercontent.com/4322250/157230879-1f6e3272-d8c9-4f1d-9233-b42edcb04f4f.png)

**Comment by myrmoteras** [comment]
This is the automated step - POA will do the QC and fix it.

the adiostola etc are species groups we have not yet properly figured out how to deal with - but we need to.

**Comment by flsimoes** [comment]
We're on to it.

I don't know why, but the authors added a full-stop in-between the name parts...
![image](https://user-images.githubusercontent.com/3343086/157234401-b9d4d9b7-3b4e-4809-b42e-e015b68bf6e0.png)

**Comment by millerjeremya** [comment]
What a strange formatting choice. 
Thanks everyone!

**Comment by gsautter** [comment]
The "formatting choice" with the period between genus and species got me curious, so I just looked at the source PDF, and it doesn't seem to have this period ... might be a highly pathological font decoding anomaly ... will take a look at the PDF after my current Skype.

**Comment by flsimoes** [comment]
> The "formatting choice" with the period between genus and species got me curious, so I just looked at the source PDF, and it doesn't seem to have this period ... might be a highly pathological font decoding anomaly ... will take a look at the PDF after my current Skype.

Thanks for looking at that Guido

**Comment by gsautter** [comment]
Reproduced the font decoding glitch ... most pathological case so far, I guess ... digging in.

**Comment by gsautter** [comment]
IMF UUID (to have it handy): `FFB269399C4D702CD44FFFD9E928FFB2`

**Comment by gsautter** [comment]
> Looks like an issue in the Unicode mapping ... something weird is going on there, most likely to the avail of conflating two characters.

Turns out the Unicode mapping _does_ actually map `0x20` (space) to `0x002E` (period) ... need to figure out what to do about this.

**Comment by gsautter** [comment]
Managed to filter out the faulty mapping now (with a one-off catch in this freak instance), re-decoded the source, uploaded the corrected IMF to the server, and re-ran the batch ... free to proceed with QC as normal now.
