### ISSUE TITLE
corrupt figure for zenodo record 22210 

### ISSUE THREAD

**Issue by punkish** [plazi/treatmentBank#43]
this one does not look right https://zenodo.org/record/222110

cc @gsautter

**Comment by gsautter** [comment]
It's a late 2016 export (see https://zenodo.org/record/222110/export/json#.YjS_Uqgo_QU), so this can very well be an error ... and then, looking at the parent publication https://zenodo.org/record/222105 (Page 10), what looks like a fading edge of a scan actually _is_ in that diagram ... just missing the words, might need repair in the IMF and re-exporting afterwards.

**Comment by gsautter** [comment]
Done, replaced the figure with a newly decoded one: https://zenodo.org/record/6369352
