### ISSUE TITLE
replace http with https in the source document

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#53]
in the UI for treatments, the source document has a http instead of a https. Can this be fixed?

https://treatment.plazi.org/GgServer/html/755A24B6FE835E30A5E3B646DF76F7AF

![image](https://user-images.githubusercontent.com/4609956/177283116-c0c20a71-6b8c-45f0-8867-c8d515468b38.png)

**Comment by gsautter** [comment]
Done.
