### ISSUE TITLE
Enable CORS on http://treatment.plazi.org/

### ISSUE THREAD

**Issue by retog** [plazi/treatmentBank#55]
For the treatments to be accessible in browser-applications we should https://enable-cors.org/.

**Comment by gsautter** [comment]
Done.

**Comment by gsautter** [comment]
Proudly announcing we now have https://en.wikipedia.org/wiki/Evil_bit compatibility, as CORS is nothing else.

**Comment by retog** [comment]
That was really amazingly fast! Thanks, @gsautter.

**Comment by gsautter** [comment]
Well, Tomcat comes with a CORS filter you can deploy ... and I'd done that already for the matching service, so only needed to change the filter pattern ...

Doesn't change my opinion that CORS is completely moot, though, as noting can _force_ clients to observe it ... just like the TCP evil bit.

**Comment by retog** [comment]
> Doesn't change my opinion that CORS is completely moot, though, as noting can force clients to observe it ... just like the TCP evil bit.

Except it's the other way round. With the header you're setting you're allowing, not denying access. Of course, people could have used browsers that allow cross-origin even if the header is not set. Now it works with the well-behaving browsers actually out there.

**Comment by gsautter** [comment]
> Except it's the other way round. With the header you're setting you're allowing, not denying access. Of course, people could have used browsers that allow cross-origin even if the header is not set. Now it works with the well-behaving browsers actually out there.

I am well aware of that ... the point was that it's not actually denying access to anyone who simple ignores the headers, so the whole model is flawed, as it only creates extra effort for well-meaning code, while being completely ineffective against non-well-meaning code, and hence nothing but obsolete overhead.

**Comment by retog** [comment]
> I am well aware of that ... the point was that it's not actually denying access to anyone who simple ignores the headers, so the whole model is flawed, as it only creates extra effort for well-meaning code, while being completely ineffective against non-well-meaning code, and hence nothing but moot, useless overhead.

No, it is effective against the attack scenarios it addresses.
Here's a scenario:
Imagine Plazi charges 1$ per treatment and has contracts with universities so that when accessing treatment bank from their networks the costs are automatically charged to the university. Now further assume plazi uses IP Ranges to determine if a request should be billed to a university (without this additional assumption, a `Access-Control-Allow-Credentials: false`-default would provide enough protection). In this scenario, the malicious website student-goodies.com could, when accessed from within the university, send code to the browser that accesses a bunch of treatments and send them back to student-goodies.com server. The users accessing the site wouldn't notice that they are being used by the operators of student-goodies.com to steal valuable treatments at the expenses of their university.

**Comment by myrmoteras** [comment]
Is this a realistic scenario for Plazi/TB where all is open anyways?

**Comment by retog** [comment]
Hi @myrmoteras , this is not a possible attack scenario in our case and the reason why we can safely enable cross-origin access to our data. I was just pointing out, that the CORS mechanism does indeed offers real protection against some attacks: it prevents malicious websites from impersonating their visitors to gain access to a third party site.

**Comment by gsautter** [comment]
> Imagine Plazi charges 1$ per treatment and has contracts with universities so that when accessing treatment bank from their networks the costs are automatically charged to the university. Now further assume plazi uses IP Ranges to determine if a request should be billed to a university (without this additional assumption, a `Access-Control-Allow-Credentials: false`-default would provide enough protection). In this scenario, the malicious website student-goodies.com could, when accessed from within the university, send code to the browser that accesses a bunch of treatments and send them back to student-goodies.com server. The users accessing the site wouldn't notice that they are being used by the operators of student-goodies.com to steal valuable treatments at the expenses of their university.

I do get this ... but it only ever works if at least the _browser_ used inside the university IP range plays along, i.e., CORS relies on client side collaboration of some sort, and there is no way of enforcing that.
