### ISSUE TITLE
add vernacular names to SRS stats

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#65]
Is it possible to add `vernacularName `to SRS stats?

There is a an increased interest from the more applied side of taxonomy to get access to the vernacular names. Important sources are for example the HBMW, MSW, etc, taxa that are widely used beyond the systematics commonity

**Comment by myrmoteras** [comment]
@gsautter is this a mere issue to add vernacular names to TB stats  or does this need more work? if not, I would add this as a long hanging fruit to the srs stats in the forseeable future.

**Comment by gsautter** [comment]
Well, I added a field group for the vernacular names now ... question is how many documents we have with the vernacular names _marked_ at all ... can only thing of the HBMW, which I did run updates for now to get some data in the new fields, but cannot seem to think of all too many more ...

**Comment by gsautter** [comment]
Well, the stats don't say too much regarding where we have vernacular names marked at this point, simply because all I re-ingested so far is the HBMWs ... we don't mark vernacular names as part of the normal batch processing so far, so the only possible source is special conversions like all the recently added mammal treatments or floras.

**Comment by myrmoteras** [comment]
it means, that the few cases where we so far annotated are also there, and we can annotate in cases we are interested in.

The stats allow to look at the treatments where a vernacular name occurs and more. 

the fact, that we can annotate this is relevant in itself.

**Comment by gsautter** [comment]
I sure see the value of having this in the stats, as well as our ability to annotate the vernacular names wherever needed ... my question was merely about how to initially populate the newly added table.
