### ISSUE TITLE
material citation not highlighted 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#66]
The combination of treatmentUUID#MCUUID should lead to a highlighted treatment. 

https://tb.plazi.org/GgServer/html/F74A2513FFF2F103FD982859FE7F0082#CF8B9E58FFF2F103FF7C28ADFAF8000A
![image](https://user-images.githubusercontent.com/4609956/203289975-7d717117-96d7-43e3-83ca-c321a864a086.png)

When using another combination from GBIF, this seems not work for this mc 	https://treatment.plazi.org/id/487187C2B217FF830F62FAAAB098F8BC#70B03C89B217FF800837F9D5B121F99E whilst it does for this 487187C2B217FF830F62FAAAB098F8BC.mc.70B03C89B217FF800C0EF9A2B525F923 which would be  	https://tb.plazi.org/GgServer/html/487187C2B217FF830F62FAAAB098F8BC#70B03C89B217FF800C0EF9A2B525F923

**Comment by gsautter** [comment]
Oh, it does work, only that the highlights are very small ... merely a single ". J" in both cases, which admittedly are barely visible ... this is a problem in the markup, not the highlighting.
