### ISSUE TITLE
uuids in all versions of xml

### ISSUE THREAD

**Issue by punkish** [plazi/treatmentBank#7]
@gsautter 

The simplified version of xmls that you make for me have IDs (uuid) in every treatment and its elements, as I had requested. Thanks. However, the versions of xmls available via tb don't have that. For example, https://tb.plazi.org/GgServer/xml/03FC87E61268FFD6D3E36CD2FE12DF29 has the following `materialsCitation`

```xml
<materialsCitation ID-GBIF-Occurrence="3392779302" collectorName="Talud XV" country="Mexico" elevation="-479m" latitude="26.54278" location="Off La Bocana" longLatPrecision="1" longitude="-113.93889" municipality="Eastern Tropical Pacific" pageId="3" pageNumber="120" specimenCount="1" stateProvince="Baja California Sur" typeStatus="holotype">
<emphasis bold="true" box="[151,310,580,606]" pageId="3" pageNumber="120">
```

and my version has the following

```xml
<materialsCitation id="3B3D3CAD1268FFDFD3E36F2DFD30DBD0" ID-GBIF-Occurrence="3392779302" collectorName="Talud XV" country="Mexico" elevation="-479m" latitude="26.54278" location="Off La Bocana" longLatPrecision="1" longitude="-113.93889" municipality="Eastern Tropical Pacific" pageId="3" pageNumber="120" specimenCount="1" stateProvince="Baja California Sur" typeStatus="holotype">
```

In my view, that `id="3B3D3CAD1268FFDFD3E36F2DFD30DBD0"` is very important because it allows one to link a record in zenodeo with a record in tb and in any other application/website that uses zenodeo data. Would it be possible to retain that element-level id in all versions of the xmls?

Many thanks,

cc @myrmoteras

**Comment by gsautter** [comment]
It is very possible to output the annotation UUIDs in TB, sure. This is simply the first request for doing so, and I used to consider them too verbose to always include in the general-purpose XML ...

Implemented including the UUIDs now, and if we ever decide we need them only on specific elements, changing that has now become a matter of configuration.

**Comment by punkish** [comment]
> and I used to consider them too verbose to always include in the general-purpose XML ...

verbose perhaps, but essential? definitely. The UUIDs are the *only* way I can identify the sub-treatment elements uniquely. For example, if I ever need to update a material citation with new or updated info, I would need to know the UUID to update the correct record in the db.

Thanks for implementing this

**Comment by gsautter** [comment]
Thing is that the historized XML has been including all the UUIDs right from the start in 2019, specifically to support applications like your system (including the deletion markers you said you couldn't do without) ... why the change of heart, why not use the historized version?

**Comment by punkish** [comment]
good question. I forget why we (I) migrated to a simplified version but perhaps having (or not having) uuids was not a part of the issue. In any case, I can try the historized version and if it does the job then you don't have to create a special one for Zenodeo. Will make the job easier. Thanks
