### ISSUE TITLE
update name in MSW1 seems not to work

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#74]
@gsautter I am trying to fix this name Barbastello that should be Barbastella

* I opened the file in GGI https://tb.plazi.org/GgServer/summary/3F3CFFD1A55CFFADFFDC34768324D72D
* I fixed the OCR error
* I fixed the attribute genus=Barbastella

it does not show up.

![image](https://user-images.githubusercontent.com/4609956/211490106-75acfec1-0fff-424e-8e81-4425768bd97a.png)

I fixed it this morning again and still does not show up.

**Comment by flsimoes** [comment]
I've opened the document and saved it again in the hopes that it helps (last version was from november 2022, so worth a go...

![image](https://user-images.githubusercontent.com/3343086/211545649-6180911c-9079-4122-bba8-41f9a44a9e99.png)

**Comment by myrmoteras** [comment]
ok - this time it works, but I am not understanding why it  takes 3 tries
