### ISSUE TITLE
SRS issue: suddenly no resutls when adding treatmentcitation

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#81]
@gsautter 
in this case https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+bib.author+bib.title+bib.pubDate+bib.year+tax.orderEpithet&groupingFields=doc.articleUuid+bib.author+bib.title+bib.pubDate+bib.year+tax.orderEpithet&FP-bib.year=2022&FP-tax.orderEpithet=Chiroptera&format=HTML
I am getting the result
![image](https://user-images.githubusercontent.com/4609956/214640957-3e76cc00-4a62-4ffd-afb0-54a224e226d9.png)

when I add `Verbatim Treatment Citation` then I get nothing 

https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+bib.author+bib.title+bib.pubDate+bib.year+tax.orderEpithet+treatCit.citString&groupingFields=doc.articleUuid+bib.author+bib.title+bib.pubDate+bib.year+tax.orderEpithet+treatCit.citString&FP-bib.year=2022&FP-tax.orderEpithet=Chiroptera&format=HTML

![image](https://user-images.githubusercontent.com/4609956/214641379-4b558aca-f186-4cda-98de-b6e7adaca68f.png)

**Comment by gsautter** [comment]
Adding the basic "Number of ... Citations" form the "Citation Data" field group (and showing the "Sum of Values" for all of them) says it all ... there simply aren't any treatment citations in any of the Chiroptera treatments published in 2022 that are in TB: https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+bib.author+bib.title+bib.year+tax.orderEpithet+cit.treatCitCount+cit.bibRefCitCount+cit.figCitCount+cit.tabCitCount&groupingFields=doc.articleUuid+bib.author+bib.title+bib.year+tax.orderEpithet&FP-bib.year=2022&FP-tax.orderEpithet=Chiroptera&format=HTML

If you look for treatments _added to the collection_ in 2022 ("Year of First Upload") instead, there are a good bunch, just none _originally published in_ 2022: https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+doc.uploadYear+bib.author+bib.title+bib.year+tax.orderEpithet+cit.treatCitCount+cit.bibRefCitCount+cit.figCitCount+cit.tabCitCount&groupingFields=doc.articleUuid+doc.uploadYear+bib.author+bib.title+bib.year+tax.orderEpithet&orderingFields=bib.year&FP-doc.uploadYear=2022-&FP-tax.orderEpithet=Chiroptera&format=HTML
or with the verbatim treatment citations (quite some data, omitted the citation count fields here): https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.articleUuid+doc.uploadYear+bib.author+bib.title+bib.year+tax.orderEpithet+treatCit.citString&groupingFields=doc.uuid+doc.articleUuid+doc.uploadYear+bib.author+bib.title+bib.year+tax.orderEpithet+treatCit.citString&orderingFields=bib.year&FP-doc.uploadYear=2022-&FP-tax.orderEpithet=Chiroptera&format=HTML
