### ISSUE TITLE
figureCitation attributes

### ISSUE THREAD

**Issue by punkish** [plazi/treatmentBank#9]
@gsautter,

To date I've been expecting a `<figureCitation>` tag to be like so

```xml
<figureCitation id="136E2A751268FFDFD279698FFEFDDC76" captionStart="FIGURE 2"
    captionStartId="4.[151,250,1471,1495]"
    captionTargetBox="[167,1422,420,1441]"
    captionTargetId="figure-155@4.[160,1427,415,1447]" captionTargetPageId="4"
    captionText="FIGURE 2. Wellstenhelia euterpoides sp. nov., female:A, habitus, dorsal; B, urosome, dorsal; C, urosome, lateral; D, urosome, ventral (P5-bearing somite omitted); E, right caudal ramus, dorsal; F, distal part of left caudal ramus, lateral; G, distal part of left caudal ramus, ventral."
    figureDoi="http://doi.org/10.5281/zenodo.5563519"
    httpUri="https://zenodo.org/record/5563519/files/figure.png" pageId="3"
    pageNumber="120">Fig. 2A</figureCitation>
```

For every **figureCitation**, I extract the **captionText** and **httpUri**. But today I noticed a much more complicated tag like so (for **treatmentId** 03FC87E61268FFD6D3E36CD2FE12DF29)

```xml
<figureCitation id="136E2A751268FFDFD3EB6CB6FE91D88F" captionStart-0="FIGURE 2"
    captionStart-1="FIGURE 3" captionStart-2="FIGURE 4"
    captionStart-3="FIGURE 5" captionStart-4="FIGURE 6"
    captionStart-5="FIGURE 7" captionStartId-0="4.[151,250,1471,1495]"
    captionStartId-1="5.[151,250,1978,2002]"
    captionStartId-2="6.[151,250,1985,2009]"
    captionStartId-3="7.[151,250,1768,1792]"
    captionStartId-4="8.[151,250,1943,1967]"
    captionStartId-5="9.[151,250,1925,1949]"
    captionTargetBox-0="[167,1422,420,1441]"
    captionTargetBox-1="[158,1425,351,1948]"
    captionTargetBox-2="[182,1401,191,1951]"
    captionTargetBox-3="[156,1431,890,1739]"
    captionTargetBox-4="[296,1288,192,1910]"
    captionTargetBox-5="[161,1424,192,1892]"
    captionTargetId-0="figure-155@4.[160,1427,415,1447]"
    captionTargetId-1="figure-96@5.[151,1436,345,1955]"
    captionTargetId-2="figure-20@6.[178,1410,181,1961]"
    captionTargetId-3="figure-333@7.[151,1436,885,1745]"
    captionTargetId-4="figure-20@8.[288,1300,181,1919]"
    captionTargetId-5="figure-17@9.[151,1436,181,1901]"
    captionTargetPageId-0="4" captionTargetPageId-1="5"
    captionTargetPageId-2="6" captionTargetPageId-3="7"
    captionTargetPageId-4="8" captionTargetPageId-5="9"
    captionText-0="FIGURE 2. Wellstenhelia euterpoides sp. nov., female:A, habitus, dorsal; B, urosome, dorsal; C, urosome, lateral; D, urosome, ventral (P5-bearing somite omitted); E, right caudal ramus, dorsal; F, distal part of left caudal ramus, lateral; G, distal part of left caudal ramus, ventral."
    captionText-1="FIGURE 3. Wellstenhelia euterpoides sp. nov., female: A, rostrum, dorsal; B, antennule, each actual segment numbered; C, antenna; D, coxa, allobasis and first exopodal segment of the antenna, another view."
    captionText-2="FIGURE 4. Wellstenhelia euterpoides sp. nov., female: A, mandible; B, maxillule."
    captionText-3="FIGURE 5. Wellstenhelia euterpoides sp. nov., female: A, maxilla; B, maxilliped."
    captionText-4="FIGURE 6. Wellstenhelia euterpoides sp. nov., female: A, P1, anterior; B, P2, anterior."
    captionText-5="FIGURE 7. Wellstenhelia euterpoides sp. nov., female: A, P3, anterior; B, P4, anterior; C, P5, anterior."
    figureDoi-0="http://doi.org/10.5281/zenodo.5563519"
    figureDoi-1="http://doi.org/10.5281/zenodo.5563521"
    figureDoi-2="http://doi.org/10.5281/zenodo.5563523"
    figureDoi-3="http://doi.org/10.5281/zenodo.5563527"
    figureDoi-4="http://doi.org/10.5281/zenodo.5563529"
    figureDoi-5="http://doi.org/10.5281/zenodo.5563531"
    httpUri-0="https://zenodo.org/record/5563519/files/figure.png"
    httpUri-1="https://zenodo.org/record/5563521/files/figure.png"
    httpUri-2="https://zenodo.org/record/5563523/files/figure.png"
    httpUri-3="https://zenodo.org/record/5563527/files/figure.png"
    httpUri-4="https://zenodo.org/record/5563529/files/figure.png"
    httpUri-5="https://zenodo.org/record/5563531/files/figure.png" pageId="3"
    pageNumber="120">Figs. 2–7</figureCitation>
```

Of course, my program extracted nothing from the above tag as the attributes it was expecting are not there, for example, instead of **httpUri**, we have **httpUri-0** and so on.

My question, is there a definitive list of such variations because if I don't know in advance what I can expect, I will not be able to extract some information. In other words, I won't know what I don't know.

**update:** I am assuming there are several cases of such compound figures. As such, having a rule for handling such cases would be tremendously helpful.

@myrmoteras

**Comment by gsautter** [comment]
@punkish this is simply the way figure citations that reference multiple figures are handled ... either there is an `httpUri` attribute, or attributes `httpUri-0`, `httpUri-1`, ..., `httpUri-N`. That's the only two ways the attributes can be (same on table citations now). All other attributes are numbered in parallel to the HTTP URIs in the latter case.
An easy way of handling this is a little loop that keeps incrementing the number until no HTTP URI with that number is found: ```
var figureCitations = [...];
function handleFigureCitations() {
	var figureCitationDoneURIs = new Object(); // tracker for which figures have been handled
	for (var c = 0; c < figureCitations.length; c++) {
		if (figureCitations[c]['httpUri']) // figure citation referencing single figure
			handleFigureCitation(figureCitations[c], null, figureCitationDoneURIs);
		else if (figureCitations[c]['httpUri-0']) // figure citation referencing multiple figures
			handleFigureCitation(figureCitations[c], 0, figureCitationDoneURIs);
	}
}
function handleFigureCitation(figureCitation, attributeSuffix, figureCitationDoneURIs) {
	if (!figureCitation['httpUri' + ((attributeSuffix != null) ? ('-' + attributeSuffix) : '')])
		return; // no HTTP URI given, e.g. because we're beyond the last one of multiple HTTP URIs
	
	//	do something with figure HTTP URI unless marked as handled before
	if (!figureCitationDoneURIs[figureCitation['httpUri' + ((attributeSuffix != null) ? ('-' + attributeSuffix) : '')]]) {
		/*
		do something with figure citation
		*/
		
		//	mark figure HTTP URI as handled
		figureCitationDoneURIs[figureCitation['httpUri' + ((attributeSuffix != null) ? ('-' + attributeSuffix) : '')]] = 'done';
	}
	if (attributeSuffix != null) // we're dealing with a multi-citation, recurse with next suffix number
		handleFigureCitation(figureCitation, (attributeSuffix + 1), figureCitationDoneURIs);
}

```

**Comment by punkish** [comment]
Thanks @gsautter. The code is not the problem for me. Figuring out how to store this in an rdbms is the problem. 

Still, knowing that the problem is finite and bounded is a good start to finding a solution for it

**Comment by gsautter** [comment]
@punkish maybe you could explode it into multiple records? With the annotation ID plus the suffix number as the key, defaulting the suffix number to 0 in the plain `httpUri` case?
Just an idea ... as is the origin of the original question I had to find an answer to, which was how to cram the attributes of multiple figures into a single `figureCitation` element in a well-defined way ... what I propose above would simply reverse that process.
