### ISSUE TITLE
articleDOIs in these two treatments are not extracted correctly

### ISSUE THREAD

**Issue by punkish** [plazi/treatmentBank#93]
see 

7097DE96D2B235C1D71E230048CF4D2D  
00D38DF4C439548A9820A10076073CBC

**Comment by flsimoes** [comment]
For 7097DE96D2B235C1D71E230048CF4D2D (the document UUID is 5C3FFC3FB93944411E585F187C387830), the DOI info is actually missing in the document.
I fixed it with the complete DOI

Not sure what caused 00D38DF4C439548A9820A10076073CBC (the document UUID is F3BFD206564F59C4967CE6267990A52E) to miss the complete DOI, maybe a wrong break in the XML.
Fixed as well
