### ISSUE TITLE
habitat vs figures: possiblity to annotate as well?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#97]
@gsautter  in this monograph series, the figures are split into Figures proper and Habitus - colorimages of the habitus. https://doi.org/10.5281/zenodo.8074943 . 
Is there a chance to annotate the habitus similar to figures so that they also show up in BLR?
tx

![image](https://github.com/plazi/treatmentBank/assets/4609956/786d9897-8de4-4ee5-aa3b-dfc9217437ec)
![image](https://github.com/plazi/treatmentBank/assets/4609956/2186238f-98d0-4f28-9eb5-fd0c743f418e)

![image](https://github.com/plazi/treatmentBank/assets/4609956/74f329b3-3589-40b6-b336-0d9c1310fde0)

**Comment by flsimoes** [comment]
Marking the captions is likely the easiest bit, but the "habitus citations", which I'm guessing are something like "Hab. 1", might require an update to GGI.

**Comment by gsautter** [comment]
If you annotate the captions, the figures should go to BLR, sure ... it's just that "Habitus" is  caption start I've never seen before, and right now we sure don't have any pattern that would catch such captions ... what does "habitus" even mean? sounds a bit like "habit" or "behavior" ...

**Comment by gsautter** [comment]
> Marking the captions is likely the easiest bit, but the "habitus citations", which I'm guessing are something like "Hab. 1", might require an update to GGI.

Most likely ... unless you mark them manually or by means of "Annotate All" and then link them manually ... how frequent is this caption start?

**Comment by gsautter** [comment]
> Marking the captions is likely the easiest bit, but the "habitus citations", which I'm guessing are something like "Hab. 1", might require an update to GGI.

Even though this would need an update, it would likely be a small one ... only need to add this specific caption start word.

Are there other such exotic caption starts you're aware of? Might just as well add those, too ...

**Comment by flsimoes** [comment]
> If you annotate the captions, the figures should go to BLR, sure ... it's just that "Habitus" is caption start I've never seen before, and right now we sure don't have any pattern that would catch such captions ... what does "habitus" even mean? sounds a bit like "habit" or "behavior" ...

habitus is the general morphology, that's why the figures with those captions are of the whole specimen.

**Comment by gsautter** [comment]
> > If you annotate the captions, the figures should go to BLR, sure ... it's just that "Habitus" is caption start I've never seen before, and right now we sure don't have any pattern that would catch such captions ... what does "habitus" even mean? sounds a bit like "habit" or "behavior" ...
> 
> habitus is the general morphology, that's why the figures with those captions are of the whole specimen.

Thanks! simply good to know ...

**Comment by myrmoteras** [comment]
> > Marking the captions is likely the easiest bit, but the "habitus citations", which I'm guessing are something like "Hab. 1", might require an update to GGI.
> 
> Even though this would need an update, it would likely be a small one ... only need to add this specific caption start word.
> 
> Are there other such exotic caption starts you're aware of? Might just as well add those, too ...

At the moment, I am not aware of. So I think we should not start another project to explore but rather add 'Habitus' and 'Hab. X' for now. The challenge might be the size of these publications.

**Comment by gsautter** [comment]
Added "Habitus" and "Hab." to the caption starts now, comes with net update. You might also be able to use a template with some custom caption start patterns to get them tagged, actually.

**Comment by flsimoes** [comment]
Thanks Guido!
