### ISSUE TITLE
malfunction of tabs in Links & Identifiers of Parent Publication

### ISSUE THREAD

**Issue by myrmoteras** [plazi/treatmentBank#99]
![image](https://github.com/plazi/treatmentBank/assets/4609956/4bc0b3e8-e6f4-4015-9161-6a1b0dc1b04c)

only one of the two tabs can be opened at the same time, and ArticleChecklistBank Dataset ID doesn't work at all 

tx for looking into this

**Comment by gsautter** [comment]
Reproduced ... really weird, as this is all generated, and all generated the same way ... digging in ...

**Comment by gsautter** [comment]
Just a typo in the definition file that controls the entire engine ... fixed.
